### ISSUE TITLE
New links

### ISSUE THREAD

**Issue by DJMogens** [cvpl-fdca/SagaLabs#1]

**Comment by DJMogens** [comment]
Red team skal bruge følgende links til vpn:

Lab.1: https://sl-p-uc1-lab1-pre-vpn.westeurope.cloudapp.azure.com/ 
Lab.2: https://sl-p-uc1-lab2-pre-vpn.westeurope.cloudapp.azure.com/ 
Lab.3: https://sl-p-uc1-lab3-pre-vpn.westeurope.cloudapp.azure.com/ 

blue team skal bruge dette:
Lab.1: https://sl-p-uc1-lab1-post-vpn.westeurope.cloudapp.azure.com/

**Comment by Tinggaard** [comment]
Solved in [b2aaa1f](https://github.com/cvpl-fdca/SagaLabs/commit/b2aaa1fddd3e83d8a2d83f83326946226821b330)
