### ISSUE TITLE
Red Team start info:

### ISSUE THREAD

**Issue by DJMogens** [cvpl-fdca/SagaLabs#2]
The Red team should know the credentials of the C2 server and RedTeamTools server. 
If they need more info, we can do this live at the event and post it into here.

C2 server (SSH): 
Ip: 10.255.255.244
Username: SagaC2
Password: vFz3fcMPsTgaQAQLZMhTdfnu0HfCICeuXtooqEwfck05CthX8XOlYq

RedTeamTools (RDP): 
Ip: 10.10.10.99
Username: RedTeam
Password: Password1234!

**Comment by Tinggaard** [comment]
Solved in [d5d5903](https://github.com/cvpl-fdca/SagaLabs/commit/d5d59032761a7181c117ce8f9048ccb12fc6fd49)
